- name: Redmineディレクトリ以下のオーナーを変更
  become: yes
  command:
    chown -R {{ redmine_dir_owner }} {{ redmine_dir }}

- name: Passengerがインストールされているか確認
  command:
    test -f /usr/local/bin/passenger-install-apache2-module -o \
         -f /opt/rh/rh-ruby24/root/usr/local/bin/passenger-install-apache2-module
  register:
    result
  failed_when: result.rc not in [0, 1]
  changed_when: false

- name: Passengerをインストール
  become: yes
  gem:
    name=passenger
    user_install=no
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: result.rc == 1

- name: PassengerのApache用モジュールのインストール
  become: yes
  command:
    passenger-install-apache2-module --auto
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: result.rc == 1

- name: PassengerのApache用モジュールの設定を取得
  command:
    passenger-install-apache2-module --snippet
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register:
    passenger_snippet_vars
  changed_when: false

- name: redmine.confが作成済みか確認
  command:
    test -f /etc/httpd/conf.d/redmine.conf
  register:
    conf_exist
  failed_when: conf_exist.rc not in [0, 1]
  changed_when: false

- name: redmine.confの作成
  become: yes
  template:
    src=redmine.conf.j2
    dest=/etc/httpd/conf.d/redmine.conf
  when: conf_exist.rc == 1

- name: Redmineに /redmine でアクセスするためのシンボリックリンク作成
  become: yes
  file:
    state=link
    src={{ redmine_dir }}/public
    dest=/var/www/html/redmine

- name: httpdの再起動
  become: yes
  service:
    name=httpd
    state=restarted
    enabled=yes
