- name: redmine サーバ構築
  hosts: redmine-servers
  roles:
    - system
    - mariadb
    - ruby
    - redmine
    - apache
    - redmine-plugins
    - redmine-themes
  post_tasks:
    - debug: msg="Redmine installation completed. Access http{{':'}}//{{ ansible_default_ipv4.address }}/redmine/ "
    - debug: msg="admin initial password= {{ redmine_admin_passwd }} "

- name: fess サーバ構築
  hosts: fess-servers
  roles:
#    - java
#    - fess
