- hosts: redmine-servers

  roles:
    - system
    - mariadb
    - ruby
    - redmine
    - apache
    - redmine-plugins

  post_tasks:
    - name: 完了
      debug:
        msg='インストールが完了しました。 http://{{ ansible_default_ipv4.address }}/redmine/ にアクセスしてください。'
